[package]
name = "Megaprompt"
version = "0.1.0"
authors = [ "Zachary Bush <zabu.other@gmail.com>" ]

[dependencies]
git2 = "*"
term = "*"
time = "*"
unix_socket = "*"
log = "*"
log4rs = "*"
num = "*"
prompt_buffer = { path = "prompt_buffer" }
chan = "*"
clap = "*"

[workspace]

[[bin]]
name = "megaprompt"
path = "src/main.rs"
