[package]

name = "Megaprompt"
version = "0.1.0"
authors = [ "Zachary Bush <zabu.other@gmail.com>" ]

[dependencies]
time = "*"
term = "*"
git2 = "*"

[dependencies.prompt_buffer]
path = "prompt_buffer"

[[bin]]
name = "megaprompt"
path = "src/main.rs"
