[package]
name = "Megaprompt"
version = "0.1.0"
authors = [ "Zachary Bush <zabu.other@gmail.com>" ]

[dependencies]
git2 = "*"
term = "*"
time = "*"
unix_socket = "*"
log = "*"
log4rs = "*"
num = "*"
clippy = "*"

[dependencies.prompt_buffer]
path = "prompt_buffer"

[[bin]]
name = "megaprompt"
path = "src/main.rs"
