[package]
name = "Megaprompt"
version = "0.1.0"
authors = [ "Zachary Bush <zabu.other@gmail.com>" ]

[dependencies]
git2 = "*"
term = "*"
time = "*"
unix_socket = "*"

[dependencies.prompt_buffer]
path = "prompt_buffer"

[dependencies.clippy]
git = "https://github.com/Manishearth/rust-clippy"

[[bin]]
name = "megaprompt"
path = "src/main.rs"
