[package]

name = "prompt_buffer"
version = "0.0.1"
authors = ["Zachary Bush <zachary.bush@meraki.net>"]

[dependencies]
term = "*"

[dependencies.clippy]
git = "https://github.com/zmbush/rust-clippy"
